url: http://sohailmahmud.github.io
baseurl: ""

# Site Settings
title: Sohail Mahmud
description: "Let's do good with tech"
keywords: "Machine Learning, Sohail Mahmud, UCTC, Software Engineer, Research, Development, Interpretability, Explainability, Causal Inference"
collections:
 blog:
    name: blog
    output: true
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
markdown: kramdown

highlighter: rouge
exclude: ["Rakefile", "LICENSE", "readme.md"]
